title: Services
description: this is about us woop
content:
  - discriminant: hero
    value:
      image: src/assets/images/hero/services/content/0/value/image.jpg
      title: A Hero
      description: A Description for hero
      cta:
        - discriminant: internalLink
          value:
            link: about-us
            linkText: internal link
        - discriminant: externalLink
          value:
            link: https://www.google.com
            linkText: an external link
